services:
  object_storage:
    image: minio/minio:RELEASE.2023-03-09T23-16-13Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
  dbadmin:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    depends_on:
      - db
volumes:
  minio_data:
  pgdata_prod:


